workflows:
  web-workflow:
    name: Web Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18
      groups:
        - google_play # If you use it for other things, but here it's for web
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web project
        script: |
          npm run build
    artifacts:
      - dist/**/*
    publishing:
      email:
        recipients:
          - dgr198213@gmail.com # Example, you should change this
        notify:
          success: true
          failure: true
