
workflows:
  # --- Tu flujo actual para Web (puedes dejarlo o borrarlo) ---
  web-workflow:
    name: Web Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web project
        script: |
          npm run build
    artifacts:
      - dist/**/*

  # --- AÑADE ESTO: Nuevo flujo para Android ---
  android-workflow:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20
      # Usamos Java 17 que es estándar para builds actuales
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install

      # PASO CLAVE: Construir el APK usando Gradle
      # Si usas Ionic/Capacitor, descomenta la línea de 'npm run build' y 'npx cap sync'
      - name: Build Android APK
        script: |
          npm run build
          npx cap sync
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      # CodeMagic buscará el APK aquí
      - android/app/build/outputs/apk/debug/*.apk
    
    publishing:
      email:
        recipients:
          - dgr198213@gmail.com
        notify:
          success: true
          failure: true
